name: CI

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: mcp
          POSTGRES_PASSWORD: mcp

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Test with pytest
      env:
        POSTGRES_URI: postgresql://mcp:mcp@postgres:5432/mcp
        POSTGRES_URI_ASYNC: postgresql+asyncpg://mcp:mcp@postgres:5432/mcp
        SQLITE_URI: sqlite:///dummy.db
        SQLITE_URI_ASYNC: sqlite+aiosqlite:///dummy.db
      run: |
        pytest

    - name: Lint with Ruff
      run: |
        ruff check --config pyproject.toml --statistics .
        ruff format --config pyproject.toml --check .
