name: CI

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install -e ".[dev]"

    - name: Lint with Ruff
      run: |
        ruff check --config pyproject.toml --statistics .
        ruff format --config pyproject.toml --check .

    - name: Test with pytest
      run: |
        pytest
